### ISSUE TITLE
[help] using tested working example in .swaksrc

### ISSUE THREAD

**Issue by spice42** [jetmore/swaks#100]
this 

`swaks --from test@test.com --h-From: '"testing" <test@test.com>' --header Subject:"thisis" --body "atest" -S`

works fine with the below in `.swaksrc`

```
-t test@duck.com
#-f test@test.com --h-From: '"test" <test@test.com>'
-s smtp.test.com:587
-tls
-au test@test.com
-ap testpass
```

for convenience id like to add  `--from test@test.com --h-From: '"testing" <test@test.com>'` to `.swaksrc` config, unable to find the correct syntax, 

pl. help/advise

**Comment by jetmore** [comment]
I'm not sure why you have -f and --h-From: on the same line.  This works (note also removing the single-quotes around the From: argument):
```
-t totest@duck.com
-f ifromtest@test.com
--h-From: "test" <test@test.com>
-s smtp.test.com:587
-tls
-au test@test.com
-ap testpass
```

**Comment by spice42** [comment]
thanks
