### ISSUE TITLE
[Help] sending the contents of a txt file as body in bash script

### ISSUE THREAD

**Issue by spice42** [jetmore/swaks#102]
trying to `cat` the contents of a `/home/test.txt` file as the body of an email

this, clearly does not work

`swaks --header Subject:"test" --body "cat '/home/test.txt'" -S`

ps: `.swaksrc` has all the details required to connect and send, and does so successfully

any help would be appreciated

**Comment by jetmore** [comment]
If you want swaks to read from the file:
`swaks [...] --body @/home/test.txt`

If you actually want to use cat:

`cat /home/test.txt | swaks [...] --body -`

**Comment by spice42** [comment]
thank you
