### ISSUE TITLE
2 swaks

### ISSUE THREAD

**Issue by celesteking** [jetmore/swaks#12]
There are 2 scripts - at the top and inside the RELEASE dir. Which one is the proper one? As `diff` shows me quite a lot of differences.

**Comment by jetmore** [comment]
The answer is that it depends on what you want it for.

The top-level swaks is just the code (no documentation) and should be used for development.

RELEASE/swaks is the "built" swaks from the last release, which includes having documentation and version information baked into the script.  However, this isn't a guarantee - the stuff in RELEASE should almost never be used directly except during the actual packaging process.  If you actually want release code, grab it from jetmore.org/john/swaks:

specific version:
https://jetmore.org/john/code/swaks/files/swaks-20190914.0.tar.gz
https://jetmore.org/john/code/swaks/files/swaks-20190914.0/swaks

Or, if you don't care about the version and just want the latest official release:
https://jetmore.org/john/code/swaks/latest.tar.gz
https://jetmore.org/john/code/swaks/latest/swaks

If you really, really, really want to pull a release version out of git for some reason, use RELEASE/swaks from the tagged version:
https://github.com/jetmore/swaks/blob/v20190914.0/RELEASE/swaks

After typing all of that, it just occurred to me why you're asking.  When you download a "release" from github it presents you a zipped up version of then entire repo.  If you're a casual user, then you're then left wondering whether to use ./swaks or ./RELEASE/swaks.  That functionality of github is really working as a side-effect, I never set that up.  In general, if you want to get a release you should grab it from https://jetmore.org/john/code/swaks/.  I'll see if I can make github's release system more useful for the way swaks' repo is designed.
