### ISSUE TITLE
--protect-prompt does not work

### ISSUE THREAD

**Issue by heiko3** [jetmore/swaks#26]
Using 20201010.0 passwords are echoed even if --protect-prompt is set. Does work with version 20190914.0.
System: Debian 10.6 (Buster), always reproducable:

> $ swaks --protect-prompt --from localpart@example.com --to localpart@example.com --au username
> Password: SECRET (expected: ******)

(Obvoius note: This is a security problem)

**Comment by jetmore** [comment]
Thanks for the report.  Is fixed, will do a release soon
