### ISSUE TITLE
replace deprecated module IO::Socket::INET6

### ISSUE THREAD

**Issue by Gilwyad** [jetmore/swaks#43]
The maintainer of this distribution has indicated that it is deprecated and no longer suitable for use. https://metacpan.org/pod/IO::Socket::INET6

Therefore Swaks should not use it.

**Comment by jetmore** [comment]
IO::Socket::INET6 is deprecated and lists IO::Socket::IP as the logical successor

**Comment by michal-josef-spacek** [comment]
@jetmore Hi, could we move forward in this issue? PR is prepared, I could help you, if you need some help.

**Comment by michal-josef-spacek** [comment]
FYI: We have discussion in Fedora package about it: https://src.fedoraproject.org/rpms/swaks/pull-request/2
