### ISSUE TITLE
change the shebang, please

### ISSUE THREAD

**Issue by ondohotola** [jetmore/swaks#52]
Can you change the shebang from

	#!/usr/bin/perl

to

	#!/usr/bin/env perl

please?

I have no idea how to create a pull request :-)-O

el

**Comment by sokarax** [comment]
> Can you change the shebang from
> 
> 
> 
> 	#!/usr/bin/perl
> 
> 
> 
> to
> 
> 
> 
> 	#!/usr/bin/env perl
> 
> 
> 
> please?
> 
> 
> 
> 
> 
> I have no idea how to create a pull request :-)-O
> 
> 
> 
> el

**Comment by jetmore** [comment]
This is done in a branch and will be released eventually but I'm not in a big hurry unless it's justified somehow. In general I think most people use swaks from a package manager, in which case the #! would be right, or if they're downloading it on their own they know enough to change the interpreter manually.

**Comment by ondohotola** [comment]
I am loading it from homebrew where perl sits in /usr/local/bin
and is not picked up.

Indeed it is not a big hurry, but perhaps just include it in the
next release.

el



On 2022-08-19 21:15 , John Jetmore wrote:
> This is done in a branch and will be released eventually but I'm
> not in a big hurry unless it's justified somehow.  In general I
> think most people use swaks from a package manager, in which
> case the #!  would be right, or if they're downloading it on
> their own they know enough to change the interpreter manually.
[...]
-- 
Dr. Eberhard W. Lisse   \         /       Obstetrician & Gynaecologist
***@***.***             / *      |  Telephone: +264 81 124 6733 (cell)
PO Box 8421 Bachbrecht  \      /  If this email is signed with GPG/PGP
10007, Namibia           ;____/  Sect 20 of Act No 4 of 2019 may apply

**Comment by jetmore** [comment]
This is a homebrew packaging issue - they're including software in their packaging system that doesn't work with other software in their packaging system.  That said, it will be released with the fix at some point

**Comment by jetmore** [comment]
This is in 6416f7bba2d1e3734cc2962a565c2bc20e0afaa9 and slated for the next release
