### ISSUE TITLE
ERROR when i send email to OUTLOOK

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [jetmore/swaks#59]
Email sent to outlook are received, but the content of any kind is unreadable 

`swaks --attach-type text/html --attach-body @mod.html --attach-type application/pdf --attach documentation.pdf -t "$email" --add-header "MIME:Version 1.0" --add-header "Content-Type: text/html"  --h-Subject "Devis pour Visite Virtuelle Google $prix€" --h-From: '"<MY NAME>" <EMAIL@gmail.com>' -s smtp.gmail.com:587 -tls -au EMAIL@gmail.com -ap jbnymdemutvqifd -f EMAIL@gmail.com --tls-protocol tlsv1_3`

**Comment by jetmore** [comment]
@jojojojojoj5564656465465  I'm willing to look at this but you need to provide some detail.  The contents of the files you're sending, the transaction where you actually send it, and the email that ends up being received on the server would all be needed to figure out what's going on

**Comment by jetmore** [comment]
feel free to reopen if there is more detail
