### ISSUE TITLE
weird command expansion in bash

### ISSUE THREAD

**Issue by devZer0** [jetmore/swaks#91]
when i do

swaks --to <email1>  --from <email2>  --server localhost --h-Subject: "Test Test!!"

the command fails with

swaks --to <email1> --from <email2> --server localhost --h-Subject:  "Test Testswaks --to <email1> --from <email2>  --server localhost --h-Subject: "Test Test!""
*** Data left in option list when processing  command line ('Test!').  Exiting

swaks version 20201014.0 (debian 12.4)

**Comment by jetmore** [comment]
It has something to do with `!!` pulling from your shell's history.  Try it either without using `!!` or using single quotes instead of double quotes (eg `'Test Test!!'`)

**Comment by jetmore** [comment]
closing as no response.  Feel free to reopen if you have more information
