### ISSUE TITLE
"--tls-protocol tlsv1" fails after upgrade to FreeBSD 14.0

### ISSUE THREAD

**Issue by usonianhorizon** [jetmore/swaks#92]
I am trying to debug an old accounting system (no longer supported by the vendor) which uses TLSv1 to send email via SMTP.  I have a dedicated SMTP server that accepts TLSv1, and have been using SWAKS to debug the interaction between the two.  (Aside: SWAKS _was_ able to talk to the SMTP server successfully, while the accounting system is still not, but this is not the issue at hand)

After upgrading a few of my machines to the latest FreeBSD version 14.0, I am now getting the follow error when running the test scripts using SWAKS:

```
<-  250-8BITMIME
<-  250-ENHANCEDSTATUSCODES
<-  250-SIZE 36700160
<-  250-DSN
<-  250-STARTTLS
<-  250 HELP
 -> STARTTLS
<-  220 2.0.0: Ready to start TLS
*** TLS startup failed (connect(): error:0A00014D:SSL routines::legacy sigalg disallowed or unsupported)
*** STARTTLS attempted but failed
```

Locally, when I run:

`$ openssl ciphers -v -s | grep TLSv1`

I still see in the ciphers list:

```
...
ECDHE-ECDSA-AES256-SHA         TLSv1   Kx=ECDH     Au=ECDSA Enc=AES(256)               Mac=SHA1
ECDHE-RSA-AES256-SHA           TLSv1   Kx=ECDH     Au=RSA   Enc=AES(256)               Mac=SHA1
ECDHE-ECDSA-AES128-SHA         TLSv1   Kx=ECDH     Au=ECDSA Enc=AES(128)               Mac=SHA1
ECDHE-RSA-AES128-SHA           TLSv1   Kx=ECDH     Au=RSA   Enc=AES(128)               Mac=SHA1
...
```

Would anyone have any suggestions on what might have happened, and what I might be able to do in order to continue to use SWAKS for a FreeBSD 14.0 machine to debug my problem?  I realize that this may come across as a FreeBSD orientated question, but I am asking in case there is something about the most recent openssl libraries (and .cnf file) that might allow me to recover TLSv1 for this testing purpose.

(I do still have a FreeBSD 13.2 machine which continues to be able to run the test script successfully.)

advTHANKSance

**Comment by polarathene** [comment]
I think I recall with a Debian upgrade (perhaps to Bullseye), the OpenSSL config they shipped adjusted the security level, which prevented connections with some cipher suites or lower TLS levels unless you modified that config to relax the security level. I needed to do that for Dovecot at the time.

It may have also become a default with OpenSSL 3.0, not sure (_I think I recall reading that they adjusted their policy for the same setting with that release though_).

While the ciphersuite may say TLSv1 there, that's where it was introduced but is still compatible with newer TLS versions, but I think it can still affect negotiating connections that don't support TLS 1.2?

---

Here you go, give this a read and try apply the same to your system? https://github.com/docker-mailserver/docker-mailserver/pull/2193

**Comment by usonianhorizon** [comment]
Thank you for this.

I had adapted the guidance from:

[Setting and Verifying TLS min version in Ubuntu 22.04](https://stackoverflow.com/q/75826162)

and the script described at:

[Reducing TLS client security requirements on OpenSSL and GnuTLS](https://passingcuriosity.com/2021/diffie-hellman-short-primes-disable/)

which are Ubuntu specific resources, on my client FreeBSD machine, but thus far have been unsuccessful.  It very well could me that I am misunderstanding the syntax of the openss.cnf file, and so the above changes are not having the desired effect.

```
[openssl_init]
providers = provider_sect
ssl_conf = ssl_sect

# List of providers to load
[provider_sect]
default = default_sect
```
...

```
[default_sect]
# activate = 1

ssl_conf = ssl_sect

[ ssl_sect ]
system_default = system_default_sect

[ system_default_sect ]
MinProtocol = TLSv1
# Be less secure when negotiating ciphers, verifying certificates, etc.
CipherString = DEFAULT:@SECLEVEL=1
```

To be clear, I am using SWAKS on my FreeBSD machine to connect to a dedicated Ubuntu 18.10, which I can confirm supports TLSv1, because my testing from a FreeBSD 13.2 was and remains successful.  It is just that I cannot seem to get the upgraded FreeBSD 14 machine to "downgrade" to talk TLSv1 to the legacy SMTP server.

_ASIDE: I did pinpoint the issue with the legacy accounting system failing to talk to the SMTP server: it uses the (optional) `initial-response` argument on the AUTH LOGIN command [RFC-4954](https://www.rfc-editor.org/rfc/rfc4954#page-3), which the version of OpenSMTPd on the server does not support.  So I am still trying to thread the needle with a server that supports TLSv1 and an SMTP server that supports the `initial-response` argument_

**Comment by usonianhorizon** [comment]
Okay, I believe that I have figured out a workaround...

My MWE /etc/ssl/openssl.cnf:

```
openssl_conf = default_conf

# Comment out the next line to ignore configuration errors
config_diagnostics = 1

[default_conf]
ssl_conf = ssl_sect

[ ssl_sect ]
system_default = system_default_sect

[ system_default_sect ]
MinProtocol = TLSv1
# Be less secure when negotiating ciphers, verifying certificates, etc.
CipherString = DEFAULT:@SECLEVEL=0
```

By setting `@SECLEVEL=0` I was able to **successfully** use SWAKS on FreeBSD 14.0 with the following options:

```
    --port 587 \
    -tls \
    --tls-protocol tlsv1
```

Given all the examples suggesting `@SECLEVEL=1` should be sufficient to downgrade to allow TLSv1, I saw only one reference to lowering that to `@SECLEVEL=0` and it **worked**!

[Ubuntu 22.04 - how to set lower SSL security level?](https://askubuntu.com/a/1450023)

and from the `man` page for `SSL_CTX_set_security_level`:

```
Level 0

    Everything is permitted. This retains compatibility with previous versions of OpenSSL.

Level 1

    The security level corresponds to a minimum of 80 bits of security. Any parameters offering below 80 bits of security are excluded. As a result RSA, DSA and DH keys shorter than 1024 bits and ECC keys shorter than 160 bits are prohibited. All export cipher suites are prohibited since they all offer less than 80 bits of security. SSL version 2 is prohibited. Any cipher suite using MD5 for the MAC is also prohibited.
```

And so maybe even Level 1 has tightened up security against TLSv1?

_Now to try and solve the `<initial-response>` optional argument being accepted by OpenSMTPd._

**Comment by polarathene** [comment]
> Given all the examples suggesting `@SECLEVEL=1` should be sufficient to downgrade to allow TLSv1, I saw only one reference to lowering that to `@SECLEVEL=0` and it **worked**!

Are you on OpenSSL 3.0? Like I said I think that release made a change related to this feature, and it may have been to adjust the levels to be more strict 🤷‍♂️ 

On prior releases `@SECLEVEL=1` probably was sufficient.

**EDIT:** Actually given the Level 1 description you shared, perhaps it was more specific to your dated mail server. It's not seriously still using 512-bit RSA key is it? :(

---

> And so maybe even Level 1 has tightened up security against TLSv1?

If not, it probably will. Pretty sure I've seen RFC in recent year or so calling to mandate TLSv1.2+ or something along those lines.

There's only a few cipher suites prior that are still safe to use IIRC, but TLS 1.0 also has some flaws that make it worse I think? Been a while since I assessed that security.

I maintain a mail server project on Github, `docker-mailserver`, and while I don't think you can use that with FreeBSD, you could probably relay mail through a modern mail server this way to the outside world. Then you have the flexibility of compatible/secure connections over 587, which can then relay to the aging mail server internally. Likewise it could send mail outbound if it needs to without falling back to unencrypted connections if there's nothing compatible.

---

**EDIT:** Ah here we go, we changed to minimum TLS 1.2 here at the end of 2022: https://github.com/docker-mailserver/docker-mailserver/pull/2945

- RFC 8996 (March 2021) deprecated TLS 1.0/1.1
- While the only issue with those cipher suites in particular seems to be:
  - The SHA-1 HMAC used, however the SHA-1 vulnerabilities I don't think are that applicable here [because of HMAC](https://crypto.stackexchange.com/questions/26510/why-is-hmac-sha1-still-considered-secure).
  - CBC cipher suite vulnerabilities, [especially in the context of TLS 1.0](https://ciphersuite.info/cs/TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA/).

**Comment by usonianhorizon** [comment]
I really appreciate the level of detail you have drilled down into.

> I maintain a mail server project on Github, `docker-mailserver`

This is an excellent idea ---one that I will explore further.

It is a (**malignant**) requirement of the legacy accounting system running on Windows, long orphaned by the vendor, and compiled against some ancient version of .NET that in order for the outbound emailing of Invoices, Purchase Orders, and the like to function, the receiving SMTP server must:

1. Accept TLSv1 connections
2. Accept the `<inital-response>` argument in the `AUTH LOGIN` command

And so I have been forced to spin up an Ubuntu 18.10 instance (which has TLSv1 still as an option), and then compile OpenSMTPd 6.8.0p1 on it (which had the fix to accept the `AUTH LOGIN <initial-response>` syntax in order to satisfy both of these requirements.

SWAKS (on my daily drive FreeBSD machine) has been invaluable in being able to pinpoint these two requirements by scouring the mail logs with tracing switched on.  Unfortunately, I haven't been able to find an option that has SWAKS use the `<initial-response>` version of the `AUTH LOGIN` command, and so have resorted to manual conversations with the SMTP server with the aid of the recipes at:

[SMTP 101: Manual SMTP Sessions](https://www.atmail.com/blog/smtp-101-manual-smtp-sessions/)

that outline a split `telnet` initial session and then a followup `openssh` session, and which I have nearly automated as an expect script.

What we have to do to keep legacy software working until an upgrade+migration can be budgeted and planned for :)

Thank you, again.

**Comment by jetmore** [comment]
@usonianhorizon are you the same person who emailed me about the initial-response issue on 2024-02-05?  Would you be willing to open a ticket for the issue?  I had never known about the initial-response variation of AUTH, but it would be fairly easy to add.  Could you include copy/paste of a session where you're authenticating manual so I have something to work against (obfuscated is fine as long as the structure is correct)

**Comment by usonianhorizon** [comment]
Indeed it was me, John.  I'll open up a separate ticket for that issue.  Thank you for the help.

Warm regards.
