### ISSUE TITLE
misleading phrasing about lack of SPF/DMARC support

### ISSUE THREAD

**Issue by uninsane** [jetmore/swaks#93]
hi, i received this message from 6 different spoofed email addresses, somebody using your tool, or maybe just somebody using the same name (202.120.11.152, `X-Mailer: swaks v20130209.0 jetmore.org/john/code/swaks/`):

> This is a test mail. If you receive this mail, it means your email server lack the authentication for SPF and DMARC. We strongly recommend you to initiate these two authentication protocols.

this is not correct. these messages were delivered to my spam folder, precisely because they didn't pass the DKIM milter. receipt of these mails *does not* mean an email server "lacks authentication for SPF and DMARC".

additionally, please consider including information in the body about who requested these tests or why. i was not expecting these messages and without any context to them i cannot tell if they're from a friendly admin trying to be a public good, or a malicious actor scanning for vulnerabilities.

**Comment by jetmore** [comment]
I am not aware of whatever project or scam is emailing you.  Swaks does not inherently know anything about SPF or DMARC.  Whatever this is, scam or helpfulness, is just using Swaks as the MTA for sending the messages.  Getting multiple copies of the mail from different senders is a pretty strong signal that this is some sort of scam (though I can't imagine what it would be unless there are malicious links in the body).
