### ISSUE TITLE
Verbosity (Log Level) or anything to make swaks quiter.

### ISSUE THREAD

**Issue by Ramalama2** [jetmore/swaks#97]
Hi, is there a way to make swaks quiter?

For example:
im using swaks inside a script to email excel row changes, (as html), its works perfectly fine, and the default logging is helpful in cases if it cannot send the email, at least you know then why.

but swaks echoes the whole body content, which can be sometimes thousands of lines.
i dont even see what usecase there is even to echo the whole body, not even for debugging purposes.

is there any way to make swaks quiter?
i mean i can make it completely shut up in my scrips with
swaks ........... > /dev/null 2>&1

but thats not really a great solution.

**Comment by jetmore** [comment]
Did you look at the docs at all?  There are so many options for this it's almost silly to quote them here.  There's an entire section of the docs on controlling the output (https://github.com/jetmore/swaks/blob/develop/RELEASE/doc/ref.txt, OUTPUT OPTIONS).  Just to name a few, --suppress-data, --hide-*, and --silent [level] are all relevant to your question

**Comment by Ramalama2** [comment]
> Did you look at the docs at all? There are so many options for this it's almost silly to quote them here. There's an entire section of the docs on controlling the output (https://github.com/jetmore/swaks/blob/develop/RELEASE/doc/ref.txt, OUTPUT OPTIONS). Just to name a few, --suppress-data, --hide-*, and --silent [level] are all relevant to your question

Thanks for the clarification, i didn't readed the docs, but the manpages of ubuntu etc.
im sorry, its super stupid that i overseen that.
thanks for the reply!

Cheers :-)
